### ISSUE TITLE
more features

### ISSUE THREAD

**Issue by jjhesk** [AndreiD/surveylib#2]
first of all, I'm so thankful to see your work done. great job! This lib looks promising. Is it possible to adding selection choices and pop up input based on previous selections?

**Comment by AndreiD** [comment]
Thanks :). Now that you remind me, I've forgot to add the Ratings "Stars" type of question. Also want to make a sample project with retrofit sending/receiving form the server, storing the answers offline if the user doesn't have internet...

what do you mean by selection choices ?

- for the popup input based on previous selections, hmmm... like to declare in the json a question with a parameter "optional, only if x condition occurred ? then how would you describe this condition ? 

You want to help coding them ? Just fork the library, and modify it and make a push request.

**Comment by mbdali** [comment]
How can i send answers to server (php) post?

**Comment by AndreiD** [comment]
check Retrofit https://github.com/square/retrofit
