### ISSUE TITLE
clearing previous answers from json string

### ISSUE THREAD

**Issue by mbdali** [AndreiD/surveylib#3]
Survey answers appends to previous answers.
how to clear all answers?

**Comment by mbdali** [comment]
i solved it. by

Answers.java
public void clear_answers()
{
    answered_hashmap.clear();
}

and changes in surveyactivity.java
 public void event_survey_completed(Answers instance) {
        Intent returnIntent = new Intent();
        returnIntent.putExtra("answers", instance.get_json_object());
        instance.clear_answers();   //added
        setResult(Activity.RESULT_OK, returnIntent);
        finish();
    }

**Comment by AndreiD** [comment]
will push it in the next version when I find some time
