### ISSUE TITLE
Description doesn't appear

### ISSUE THREAD

**Issue by sorrento** [AndreiD/surveylib#6]
Hi, 
in the example example1.json, there is a description "(Select all that apply)", that actually doesnt' appear in the survey. Is it maybe  that the font color is the same as the background? (white).

**UPDATE** as @CrandellWS pointed out, it's just that it is not implemented. It should be in `FragmentCheckBoxes.java` and its xml. Thanks

**Comment by CrandellWS** [comment]
the method does not seem to ever get used https://github.com/AndreiD/surveylib/search?utf8=%E2%9C%93&q=getDescription

have a look at: https://github.com/AndreiD/surveylib/blob/31323221186bde4f27b1ac224e6b8361263e858e/surveylib/src/main/java/com/androidadvance/androidsurvey/SurveyActivity.java#L62

**Comment by CrandellWS** [comment]
As an example the referenced question happens to a be a checkbox so it will use

https://github.com/AndreiD/surveylib/blob/master/surveylib/src/main/java/com/androidadvance/androidsurvey/fragment/FragmentCheckboxes.java

and 

https://github.com/AndreiD/surveylib/blob/master/surveylib/src/main/res/layout/fragment_checkboxes.xml

**Comment by AndreiD** [comment]
Listen people... This is not fitting to be a library
I was thinking that people who use this "library" better just download the files, copy paste them, and easily edit them, because in 99% it would require custom stuff

**Comment by AlexMuriithi** [comment]
Was the issue on displaying the Description working? I'm using the Library and it seems not to display description. Please explain how we are supposed to use this feature

**Comment by AndreiD** [comment]
you think I remember man. after all this time

**Comment by CrandellWS** [comment]
@AlexMuriithi see my comments https://github.com/AndreiD/surveylib/issues/6#issuecomment-203585724
take notice of `textview_q_title` and copy how the title is loaded but make it for the description. 

@AndreiD it's all good, your work helped me thank you.

**Comment by AlexMuriithi** [comment]
@CrandellWS Thank you it worked as per your instructions. Appreciated.
